# This file can be used to install module depdencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  symlinks:
    wls_profile: "#{source_dir}"
  repositories:
    facts:               'https://github.com/puppetlabs/puppetlabs-facts.git'
    puppet_agent:        'https://github.com/puppetlabs/puppetlabs-puppet_agent.git'
    provision:           'https://github.com/puppetlabs/provision.git'
  forge_modules:
    easy_type:              enterprisemodules-easy_type
    wls_install:            enterprisemodules-wls_install
    wls_config:             enterprisemodules-wls_config
    stdlib:                 puppetlabs-stdlib
    echo:                   ipcrm-echo
    archive:                puppet-archive
    augeas_core:            puppetlabs-augeas_core
    augeasproviders_core:   puppet-augeasproviders_core
    augeasproviders_sysctl: puppet-augeasproviders_sysctl
    limits:                 saz-limits
    firewall:               puppetlabs-firewall
    firewalld:              puppet-firewalld
    sleep:                  fiddyspence-sleep
    java:                   puppetlabs-java
    sshkeys_core:           puppetlabs-sshkeys_core
