---
include:
- project: enterprisemodules/gitlab_ci
  file: module-defaults.yml

WebLogic 12.2.1.2  Acc test:
  extends: ".puppet_acceptance_test"
  variables:
    type: admin_server_wls12212
  only:
    changes:
    - lib/puppet/**/*.rb
    - templates/**/*.*
    - manifests/**/*.pp
    - specs/support/acceptance/**/*.rb
    - specs/acceptance/admin_server_spec.rb
WebLogic 12.2.1.3  Acc test:
  extends: ".puppet_acceptance_test"
  variables:
    type: admin_server_wls12213
  only:
    changes:
    - lib/puppet/**/*.rb
    - templates/**/*.*
    - manifests/**/*.pp
    - specs/support/acceptance/**/*.rb
    - specs/acceptance/admin_server_spec.rb
